### ISSUE TITLE
Writing MBus Data to MariaDB - Version Problems with Python - Problem with slave address

### ISSUE THREAD

**Issue by vitus2** [packom/pyMbusHat#1]
I´m trying to read out data of 2 heat meters (Allmess Integral-V UltraLite PRO 1.5) with pyMbusHat and write them into a MariaDB.
My System:
- Raspberry 3B+
- Raspbian GNU/Linux 10 (buster) (Lite Version)
- 10.3.27-MariaDB-0+deb10u1 Raspbian 10

What I´m _able_ to do:
If I connect only 1 meter to the hat, I can read it out with py_mbus_hat.py and slave_address=0.
This are the results (only header) of the 2 separately connected meters at slave_address=0:

device 1: 
>_"access_no": 30,
> "identification": "0x21, 0x44, 0x43, 0x21",
> "manufacturer": "ITR",
> "medium": "0x4",
> "sign": "0x0, 0x0",
> "status": "0x0",
> "type": "0x72",
> "version": "0x17"_

device 2: 
>_"access_no": 38,
>"identification": "0x21, 0x44, 0x43, 0x18",
>"manufacturer": "ITR",
>"medium": "0x4",
>"sign": "0x0, 0x0",
>"status": "0x10",
>"type": "0x72",
>"version": "0x17"_

**Question 1:** How can I read out the two(or more) meters connected both to the hat? More specific: What ist the appropriate value for slave_address, or how can I find out? I tried 0, 1, 30, 38, 0x21, 0x18 - Result: Failed to read data from slave at address xy

**Question 2:** this pyMbusHat software requires an older version of python as the Python/MariaDB connector does. Is there a (easy) way to use Python 3 with pyMbusHat? My experience in Python is small - I would try to write the data with python 2 in a local .csv file, then use a seperate python 3 script to imort th .csv data in MariaDB...

**Comment by packom** [comment]
1)

Normally you can manually configure the slave's M-Bus address using a menu system on the meter.  0 is an address for unconfigured meters.  The meter instructions may indicate how to configure the slave address.

If you can't work out how to reconfigure the address, you can use libmbus to do this via the bus itself: https://github.com/rscada/libmbus - see command mbus-serial-set-address

2)

What problems are you having using pyMbusHat with python3?  You'll need to modify the install instructions as follows:

```
sudo apt install python3-pip python3-rpi.gpio
sudo pip3 install serial
git clone https://github.com/ganehag/pyMeterBus
cd pyMeterBus & sudo pip3 install -r requirements & sudo python3 setup.py install & cd ..
```

THen you should be able to run it with:
```
python3 py_mbus_hat.py
```

**Comment by vitus2** [comment]
Hi!
1. Many thanks, that sounds good! I will try it out.
2. Regarding the python3 trouble, I got a ModuleNotFoundError: No module named 'serial'....
Just tried to install as you wrote, in the last line I got this message:
`Could not open requirements file: [Errno 2] No such file or directory: 'requirements'`
I´ve not to much time today, I will try out and report later.
So far **many thanks** for your quick help!
Best regards, Vitus

**Comment by packom** [comment]
Ah - the last line above should have been:

```
cd pyMeterBus & sudo pip3 install -r requirements.txt & sudo python3 setup.py install & cd ..
```

**Comment by vitus2** [comment]
Hi!
It worked well. I managed to change the M-Bus address via libmbus (It´s necessary to do it one by one, because if there are 2 Adress 0 meters online, it will change both to th new adress...). the following link was very helpful: [https://piers.rocks/2020/04/11/mbus-primary-and-secondary-addresses.html](https://piers.rocks/2020/04/11/mbus-primary-and-secondary-addresses.html) Thanks to (you,) Piers!

PyMeterBus runs now with python3 - I now will try to find a smart solution to put the data into the mariaDB.

Best regards, Vitus

**Comment by packom** [comment]
No problem - glad you got it working!
